# name: Laravel

# on:
#   push:
#    branches:
#       - main
#   pull_request:
#    branches:
#       - main

# jobs:
#   laravel-tests:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#       with:
#         php-version: '7.4'
#     - uses: actions/checkout@v2.1.0

    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    # - name: Install Dependencies
    #   run: composer update
    # - name: Generate key
    #   run: php artisan key:generate
    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache
    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: vendor/bin/phpunit
    # - name: FTP-Deploy-Action
    #   uses: SamKirkland/FTP-Deploy-Action@3.1.1
    #   with:
    #     ftp-server: ${{ secrets.FTP_SERVER }} # configure .git-ftp-include
    #     ftp-username: ${{ secrets.FTP_USERNAME }}
    #     ftp-password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: toupload
# name: Laravel
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
# jobs:
#   FTP-Deploy-Action:
#     name: FTP-Deploy-Action
#     runs-on: ubuntu-latest
#     steps:
#     - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#       with:
#         php-version: '7.4'
#     - uses: actions/checkout@v2.1.0
#       with:
#         fetch-depth: 2
#     - name: Copy .env
#       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#     - name: Install Dependencies
#       run: composer update
#     - name: Generate key
#       run: php artisan key:generate
#     - name: Directory Permissions
#       run: chmod -R 777 storage bootstrap/cache
#     - name: FTP-Deploy-Action
#       uses: SamKirkland/FTP-Deploy-Action@4.0.0
#       with:
#         server: ${{ secrets.FTP_SERVER }}
#         username: ${{ secrets.FTP_USERNAME }}
#         password: ${{ secrets.FTP_PASSWORD }}



name: Publish Website to Web Hosting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        script: 'cd /var/www/html && ./deployer.sh'